In [3]:
!pip install Numpy  # installing numpy in jupyter notebook

In [4]:
import numpy as np

In [5]:
list=[1,2,3,4]

In [6]:
type(list)

list

In [7]:
arr=np.array(list)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr.size

4

In [11]:
z=np.zeros(10)

In [12]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
z=np.ones(10)

In [14]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# one dimensional array

In [15]:
o=np.array([1,2,3,4])

In [16]:
o

array([1, 2, 3, 4])

In [18]:
o.ndim  # to know the dimension of the array

1

In [19]:
o.shape

(4,)

In [28]:
#2-d array
x=np.array([[1,2,3],[4,5,6],[7,8,9],[3,5,8]])

In [29]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 5, 8]])

In [30]:
x.ndim

2

In [31]:
x.shape

(4, 3)

In [32]:
#3-d array
x=x.reshape(3,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 3],
        [5, 8]]])

In [33]:
x.ndim

3

In [34]:
x.shape

(3, 2, 2)

In [42]:
x=x.reshape(3,4)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 5, 8]])

In [40]:
x.ndim

2

In [41]:
x.shape

(3, 4)

# Indexing

In [43]:
arr=np.array([1,2,3,4])

In [44]:
arr[2]

3

In [45]:
arr[1]+arr[3]

6

In [46]:
#2-d array accessing 

In [49]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [50]:
print("2 element in 1st dim",arr[0,1])

2 element in 1st dim 2


In [52]:
print("2 element in 1st dim",arr[1,1])

2 element in 1st dim 7


In [54]:
print("2 element in 1st dim",arr[1,4])

2 element in 1st dim 10


In [55]:
#linspace (start,end,number of values)

In [56]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [58]:
x=np.eye(3)

In [59]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
x.shape

(3, 3)

In [61]:
np.random.randint(0,10,5)

array([0, 0, 1, 5, 9])

In [62]:
np.random.rand(3,3)

array([[0.50267364, 0.52465222, 0.18468112],
       [0.66352374, 0.04618595, 0.84693946],
       [0.4191358 , 0.56216033, 0.20309218]])

In [63]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
arr.max()

10

In [67]:
arr.min()

1

In [68]:
arr.argmax()

9

In [69]:
arr.ndim

2

In [76]:
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

# Slicing

In [77]:
a

array([ 0,  2,  4,  6,  8, 10])

In [80]:
a[1:2+1] # [start value : end index + 1]

array([2, 4])

In [81]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [82]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [85]:
a[0:0+1,0:1+1] #[column s:e+1 , row s:e+1]

array([[1, 2]])

In [86]:
a[0:1,1:3]

array([[2, 3]])

In [93]:
a[2:3,0:2]

array([[4, 5]])

In [94]:
a[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [95]:
a[1:3,1:3]

array([[3, 4],
       [5, 6]])

In [96]:
a[1:,1:]

array([[3, 4],
       [5, 6]])

In [97]:
## add two arrays

In [100]:
a=np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [102]:
a1=np.arange(0,11,2)
a1

array([ 0,  2,  4,  6,  8, 10])

In [103]:
c=a+a1
c

array([ 0,  4,  8, 12, 16, 20])

In [104]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [105]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [109]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [108]:
arr

array([1, 2, 3, 4, 5])

In [110]:
x

array([1, 2, 3, 4, 5])

In [111]:
# create an array 5*5 which contains from 0 to 24

In [115]:
a=np.arange(25)

In [116]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [117]:
a=a.reshape(5,5)

In [118]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [122]:
b=np.arange(25).reshape(5,5)

In [123]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])